# Generated by Django 3.0.2 on 2020-01-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=True, max_length=50)),
                ('coress_author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=253)),
                ('alt_email', models.EmailField(max_length=253)),
                ('phone', models.BigIntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
