# Generated by Django 3.0.2 on 2020-01-09 11:54

import core.storageback
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='file',
            field=models.FileField(storage=core.storageback.PublicMediaStorage, upload_to=''),
        ),
    ]
