# Generated by Django 3.0.2 on 2020-01-09 12:02

import core.storageback
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='file',
            field=models.FileField(editable=False, null=True, storage=core.storageback.PublicMediaStorage, upload_to=''),
        ),
    ]
