# Generated by Django 3.0.2 on 2020-01-09 12:08

import core.storageback
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200109_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='file',
            field=models.FileField(default=1, storage=core.storageback.PublicMediaStorage, upload_to=''),
            preserve_default=False,
        ),
    ]
